development: &default
  adapter: postgresql
  encoding: unicode
  database: engirunners_dev
  host: localhost
  pool: 5
  username: postgres
  password: 123456
  timeout: 5000

test:
  <<: *default
  database: engirunners_test

production:
  <<: *default
  database: engirunners_prod
